In [27]:
import numpy as np

In [28]:
a = np.array([20,30,40,50])

In [29]:
b= np.arange(4)

In [30]:
b

array([0, 1, 2, 3])

In [31]:
c = a - b

In [32]:
c

array([20, 29, 38, 47])

In [33]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [34]:
a < 35

array([ True,  True, False, False])

In [35]:
A = np.array([[1, 1], [0, 1]])


In [36]:
B = np.array([[2, 0], [3, 4]])

In [37]:
A * B

array([[2, 0],
       [0, 4]])

In [38]:
A @ B

array([[5, 4],
       [3, 4]])

In [39]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [40]:
rg = np.random.default_rng(1) 

In [41]:
a = np.ones((2, 3), dtype=int)

In [42]:
print(a)

[[1 1 1]
 [1 1 1]]
