In [49]:
import numpy as np

In [50]:
a = np.array([20,30,40,50])

In [51]:
b= np.arange(4)

In [52]:
b

array([0, 1, 2, 3])

In [53]:
c = a - b

In [54]:
c

array([20, 29, 38, 47])

In [55]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [56]:
a < 35

array([ True,  True, False, False])

In [57]:
A = np.array([[1, 1], [0, 1]])


In [58]:
B = np.array([[2, 0], [3, 4]])

In [59]:
A * B

array([[2, 0],
       [0, 4]])

In [60]:
A @ B

array([[5, 4],
       [3, 4]])

In [61]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [62]:
rg = np.random.default_rng(1) 

In [63]:
a = np.ones((2, 3), dtype=int)

In [64]:
print(a)

[[1 1 1]
 [1 1 1]]


In [65]:
b = rg.random((2,3))

In [66]:
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [67]:
a *= 3

In [68]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [69]:
b += a

In [70]:
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [71]:
#Upcasting

In [72]:
#Day 5
#Accessing and changing specific elements in rows,columns,etc
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [73]:
#Getting a specific element [r,c]
a[1,5]

13

In [74]:
#Getting specific row
# we use : to get all columns
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [75]:
#Getting a specific column
a[:,2]

array([ 3, 10])

In [78]:
#Getting a little more fancy [Startindex:enindex:stepsize
a[0, 1:6:1]

array([2, 3, 4, 5, 6])

In [79]:
#Changing elements
a[1,5] = 22
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 22 14]]


In [80]:
a[:,2] =5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 22 14]]


In [81]:
a[:,2] = 18,50
print(a)

[[ 1  2 18  4  5  6  7]
 [ 8  9 50 11 12 22 14]]


In [82]:
#3d examples
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [88]:
#Get specific element (Work outside in)
b[0,1,1]

4

In [92]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [94]:
#replace
b[:,1,:] = [[9,9],[8,8]]
print(b)


[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [95]:
#Initializing different types of arrays
#All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [100]:
#All 1s matrixs
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [102]:
#Any other number
np.full((2,3), 24)

array([[24, 24, 24],
       [24, 24, 24]])

In [103]:
#any otehrnumber(full_like, using the shape of another already existing array)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [104]:
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [106]:
#Random decimal number
np.random.rand(2,4)

array([[0.85012987, 0.05664684, 0.70125276, 0.07892648],
       [0.06689911, 0.36934766, 0.45301802, 0.56064482]])

In [107]:
np.random.random_sample(a.shape)

array([[0.67234812, 0.57149698, 0.31414552, 0.56485837, 0.26759989,
        0.19399727, 0.56932204],
       [0.43451869, 0.36772468, 0.52327529, 0.83907089, 0.62621386,
        0.72952181, 0.2676846 ]])

In [121]:
np.random.randint(2,6, size=(3,7))

array([[3, 3, 2, 2, 5, 2, 4],
       [3, 4, 5, 3, 4, 5, 2],
       [2, 5, 2, 5, 2, 5, 4]])

In [123]:
#The identity maatrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [126]:
#repeating an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [133]:
x = np.ones((5,5))
print(x)
z = np.zeros((3,3))
print(z)
z[1,1] =9
print(z)
x[1:-1,1:-1] = z
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [142]:
#be careful while coping arrays!!
a = np.array([1,2,3])
print(a)
#b = a
b = a.copy()
print(b)
b[0] = 100
print(b)
print(a)



[1 2 3]
[1 2 3]
[100   2   3]
[1 2 3]
